# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  version: 2.1
  test:
    jobs:
      - test-3_7
      - test-3_6

jobs:
  test-3_7: &test-template
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # Install required third-party packages
      - run: sudo apt-get update
      - run: sudo apt-get install csh mummer ncbi-blast+

      # Install Python code/dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools virtualenv
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install -e .  # Install the repo as a package

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      # run tests!
      # common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -v --cov=pyani --cov-report xml:.coverage.xml

      - store_artifacts:
          path: test-reports
          destination: test-reports
      - store_artifacts:
          path: .coverage.xml
          destination: .coverage.xml

      - codecov/upload:
          file: .coverage.xml


  test-3_6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6.8
